import React from 'react';
import { Info, ShieldAlert } from 'lucide-react';

interface DisclaimerBannerProps {
  variant?: 'standard' | 'warning';
}

export const DisclaimerBanner: React.FC<DisclaimerBannerProps> = ({ variant = 'standard' }) => {
  if (variant === 'warning') {
    return (
      <div
        id="agricultural-safety-warning-banner"
        className="rounded-2xl p-4.5 bg-amber-50/90 border border-amber-300/80 text-amber-950 flex items-start gap-3 text-xs sm:text-sm leading-relaxed shadow-2xs"
      >
        <ShieldAlert className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
        <div>
          <strong className="font-bold block mb-0.5 text-amber-900">Agricultural Diagnostic Advisory:</strong>
          Predictions generated by this system are AI-derived probabilistic estimations designed as a field decision-support tool. They do not constitute an official laboratory phytosanitary certification. For commercial crop interventions, always verify with your local Agricultural Extension Service or certified agronomist before spraying high-cost chemicals.
        </div>
      </div>
    );
  }

  return (
    <div
      id="agricultural-safety-standard-banner"
      className="rounded-2xl p-4 bg-emerald-50/70 border border-emerald-200/80 text-emerald-950 flex items-start gap-3 text-xs sm:text-sm leading-relaxed shadow-2xs"
    >
      <Info className="w-4.5 h-4.5 text-emerald-700 shrink-0 mt-0.5" />
      <div>
        <span className="font-bold text-emerald-900">AI-Based Decision Support:</span> Predictions and recommendations are AI estimations based on visual foliar patterns. Inspect multiple leaves across the field canopy to confirm diagnostic consistency.
      </div>
    </div>
  );
};
